const ACTION_TYPES = 
{
    FETCH_ALL_ACTIVITY_LOGS_START: 'FETCH_ALL_ACTIVITY_LOGS_START',
    FETCH_ALL_ACTIVITY_LOGS_SUCCESS: 'FETCH_ALL_ACTIVITY_LOGS_SUCCESS',
    FETCH_ALL_ACTIVITY_LOGS_FAILED: 'FETCH_ALL_ACTIVITY_LOGS_FAILED',

    FIND_ACTIVITY_LOG_BY_ID_START: 'FIND_ACTIVITY_LOG_BY_ID_START',
    FIND_ACTIVITY_LOG_BY_ID_SUCCESS: 'FIND_ACTIVITY_LOG_BY_ID_SUCCESS',
    FIND_ACTIVITY_LOG_BY_ID_FAILED: 'FIND_ACTIVITY_LOG_BY_ID_FAILED',

    CREATE_ACTIVITY_LOG_START: 'CREATE_ACTIVITY_LOG_START',
    CREATE_ACTIVITY_LOG_SUCCESS: 'CREATE_ACTIVITY_LOG_SUCCESS',
    CREATE_ACTIVITY_LOG_FAILED: 'CREATE_ACTIVITY_LOG_FAILED',

    UPDATE_ACTIVITY_LOG_START: 'UPDATE_ACTIVITY_LOG_START',
    UPDATE_ACTIVITY_LOG_SUCCESS: 'UPDATE_ACTIVITY_LOG_SUCCESS',
    UPDATE_ACTIVITY_LOG_FAILED: 'UPDATE_ACTIVITY_LOG_FAILED',

    DELETE_ACTIVITY_LOGS_START: 'DELETE_ACTIVITY_LOGS_START',
    DELETE_ACTIVITY_LOGS_SUCCESS: 'DELETE_ACTIVITY_LOGS_SUCCESS',
    DELETE_ACTIVITY_LOGS_FAILED: 'DELETE_ACTIVITY_LOGS_FAILED',

    CLEAR_ACTIVITY_LOG_ERRORS: 'CLEAR_ACTIVITY_LOG_ERRORS'
};

export default ACTION_TYPES;