const ACTION_TYPES = 
{
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',

    TOGGLE_VIDEO_MANAGEMENT: 'TOGGLE_VIDEO_MANAGEMENT',
    SELECT_VIDEO_MANAGEMENT_AUTHORS: 'SELECT_VIDEO_MANAGEMENT_AUTHORS',
    SELECT_VIDEO_MANAGEMENT_CASTS: 'SELECT_VIDEO_MANAGEMENT_CASTS',
    SELECT_VIDEO_MANAGEMENT_DIRECTORS: 'SELECT_VIDEO_MANAGEMENT_DIRECTORS',
    SELECT_VIDEO_MANAGEMENT_GENRES: 'SELECT_VIDEO_MANAGEMENT_GENRES',
    SELECT_VIDEO_MANAGEMENT_MOVIES: 'SELECT_VIDEO_MANAGEMENT_MOVIES',
    SELECT_VIDEO_MANAGEMENT_COMING_SOON_MOVIES: 'SELECT_VIDEO_MANAGEMENT_COMING_SOON_MOVIES',

    TOGGLE_SECOND_LIST_ITEM: 'TOGGLE_SECOND_LIST_ITEM',

    SELECT_DASHBOARD: 'SELECT_DASHBOARD',

    SELECT_ACCESS_RIGHT: 'SELECT_ACCESS_RIGHT'
};

export default ACTION_TYPES