const ACTION_TYPES = 
{
    TOGGLE_DRAWER: 'TOGGLE_DRAWER',

    TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',
    DROPDOWN_OPEN_ITEM_ONE: 'DROPDOWN_OPEN_ITEM_ONE',
    DROPDOWN_OPEN_ITEM_TWO: 'DROPDOWN_OPEN_ITEM_TWO',

    TOGGLE_SECOND_LIST_ITEM: 'TOGGLE_SECOND_LIST_ITEM',
};

export default ACTION_TYPES