const ACTION_TYPES = 
{
    FETCH_ALL_ACCESS_RIGHTS_START: 'FETCH_ALL_ACCESS_RIGHTS_START',
    FETCH_ALL_ACCESS_RIGHTS_SUCCESS: 'FETCH_ALL_ACCESS_RIGHTS_SUCCESS',
    FETCH_ALL_ACCESS_RIGHTS_FAILED: 'FETCH_ALL_ACCESS_RIGHTS_FAILED',

    FETCH_ALL_PERMISSIONS_START: 'FETCH_ALL_PERMISSIONS_START',
    FETCH_ALL_PERMISSIONS_SUCCESS: 'FETCH_ALL_PERMISSIONS_SUCCESS',
    FETCH_ALL_PERMISSIONS_FAILED: 'FETCH_ALL_PERMISSIONS_FAILED',

    FIND_ACCESS_RIGHT_BY_ID_START: 'FIND_ACCESS_RIGHT_BY_ID_START',
    FIND_ACCESS_RIGHT_BY_ID_SUCCESS: 'FIND_ACCESS_RIGHT_BY_ID_SUCCESS',
    FIND_ACCESS_RIGHT_BY_ID_FAILED: 'FIND_ACCESS_RIGHT_BY_ID_FAILED',

    CREATE_ACCESS_RIGHT_START: 'CREATE_ACCESS_RIGHT_START',
    CREATE_ACCESS_RIGHT_SUCCESS: 'CREATE_ACCESS_RIGHT_SUCCESS',
    CREATE_ACCESS_RIGHT_FAILED: 'CREATE_ACCESS_RIGHT_FAILED',

    UPDATE_ACCESS_RIGHT_START: 'UPDATE_ACCESS_RIGHT_START',
    UPDATE_ACCESS_RIGHT_SUCCESS: 'UPDATE_ACCESS_RIGHT_SUCCESS',
    UPDATE_ACCESS_RIGHT_FAILED: 'UPDATE_ACCESS_RIGHT_FAILED',

    DELETE_ACCESS_RIGHTS_START: 'DELETE_ACCESS_RIGHTS_START',
    DELETE_ACCESS_RIGHTS_SUCCESS: 'DELETE_ACCESS_RIGHTS_SUCCESS',
    DELETE_ACCESS_RIGHTS_FAILED: 'DELETE_ACCESS_RIGHTS_FAILED',

    CLEAR_ACCESS_RIGHT_ERRORS: 'CLEAR_ACCESS_RIGHT_ERRORS'
};

export default ACTION_TYPES;