const ACTION_TYPES = 
{
    FETCH_ALL_SUBSCRIPTIONS_START: 'FETCH_ALL_SUBSCRIPTIONS_START',
    FETCH_ALL_SUBSCRIPTIONS_SUCCESS: 'FETCH_ALL_SUBSCRIPTIONS_SUCCESS',
    FETCH_ALL_SUBSCRIPTIONS_FAILED: 'FETCH_ALL_SUBSCRIPTIONS_FAILED'
};

export default ACTION_TYPES;