const ACTION_TYPES = 
{
    FETCH_ALL_SUBSCRIPTIONS_START: 'FETCH_ALL_SUBSCRIPTIONS_START',
    FETCH_ALL_SUBSCRIPTIONS_SUCCESS: 'FETCH_ALL_SUBSCRIPTIONS_SUCCESS',
    FETCH_ALL_SUBSCRIPTIONS_FAILED: 'FETCH_ALL_SUBSCRIPTIONS_FAILED',

    FETCH_SUBSCRIPTION_BY_USER_ID_START: 'FETCH_SUBSCRIPTION_BY_USER_ID_START',
    FETCH_SUBSCRIPTION_BY_USER_ID_SUCCESS: 'FETCH_SUBSCRIPTION_BY_USER_ID_SUCCESS',
    FETCH_SUBSCRIPTION_BY_USER_ID_FAILED: 'FETCH_SUBSCRIPTION_BY_USER_ID_FAILED',
};

export default ACTION_TYPES;