const ACTION_TYPES = 
{
    FETCH_ALL_PAYMONGO_WEBHOOKS_START: 'FETCH_ALL_PAYMONGO_WEBHOOKS_START',
    FETCH_ALL_PAYMONGO_WEBHOOKS_SUCCESS: 'FETCH_ALL_PAYMONGO_WEBHOOKS_SUCCESS',
    FETCH_ALL_PAYMONGO_WEBHOOKS_FAILED: 'FETCH_ALL_PAYMONGO_WEBHOOKS_FAILED',

    CLEAR_PAYMONGO_WEBHOOK_ERRORS: 'CLEAR_PAYMONGO_WEBHOOK_ERRORS',
};

export default ACTION_TYPES;