const ACTION_TYPES = 
{
    FETCH_ALL_USERS_START: 'FETCH_ALL_USERS_START',
    FETCH_ALL_USERS_SUCCESS: 'FETCH_ALL_USERS_SUCCESS',
    FETCH_ALL_USERS_FAILED: 'FETCH_ALL_USERS_FAILED',

    UPDATE_USER_EMAIL_START: 'UPDATE_USER_EMAIL_START',
    UPDATE_USER_EMAIL_SUCCESS: 'UPDATE_USER_EMAIL_SUCCESS',
    UPDATE_USER_EMAIL_FAILED: 'UPDATE_USER_EMAIL_FAILED',

    UPDATE_USER_PASSWORD_START: 'UPDATE_USER_PASSWORD_START',
    UPDATE_USER_PASSWORD_SUCCESS: 'UPDATE_USER_PASSWORD_SUCCESS',
    UPDATE_USER_PASSWORD_FAILED: 'UPDATE_USER_PASSWORD_FAILED',

    CLEAR_USER_ERRORS: 'CLEAR_USER_ERRORS'
};

export default ACTION_TYPES;