const ACTION_TYPES =
{
    INDEX: 'INDEX_POSTS',
    INDEX_SUCCESS: 'INDEX_POSTS_SUCCESS',
    INDEX_FAILED: 'INDEX_POSTS_FAILED',

    CREATE: 'CREATE_POST',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILED :'CREATE_POST_FAILED',

    DESTROY: 'DELETE_POST',
    DESTROY_POST_SUCCESS: 'DESTROY_POST_SUCCESS',
    DESTROY_POST_FAILED :'DESTROY_POST_FAILED',
};  

export default ACTION_TYPES;