const ACTION_TYPES = 
{
    FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_START: 'FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_START',
    FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_SUCCESS: 'FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_SUCCESS',
    FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_FAILED: 'FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_FAILED',
};

export default ACTION_TYPES;