const ACTION_TYPES = 
{
    FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_START: 'FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_START',
    FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_SUCCESS: 'FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_SUCCESS',
    FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_FAILED: 'FETCH_ALL_PAYMENT_AUTHORIZATION_NOTIFICATIONS_FAILED',

    MARK_ALL_PAYMENT_AUTH_NOTIFICATIONS_AS_READ_START: 'MARK_ALL_PAYMENT_AUTH_NOTIFICATIONS_AS_READ_START',
    MARK_ALL_PAYMENT_AUTH_NOTIFICATIONS_AS_READ_SUCCESS: 'MARK_ALL_PAYMENT_AUTH_NOTIFICATIONS_AS_READ_SUCCESS',
    MARK_ALL_PAYMENT_AUTH_NOTIFICATIONS_AS_READ_FAILED: 'MARK_ALL_PAYMENT_AUTH_NOTIFICATIONS_AS_READ_FAILED'
};

export default ACTION_TYPES;