const ACTION_TYPES = 
{
    FETCH_ALL_CASTS_START: 'FETCH_ALL_CASTS_START',
    FETCH_ALL_CASTS_SUCCESS: 'FETCH_ALL_CASTS_SUCCESS',
    FETCH_ALL_CASTS_FAILED: 'FETCH_ALL_CASTS_FAILED',

    FIND_CAST_BY_ID_START: 'FIND_CAST_BY_ID_START',
    FIND_CAST_BY_ID_SUCCESS: 'FIND_CAST_BY_ID_SUCCESS',
    FIND_CAST_BY_ID_FAILED: 'FIND_CAST_BY_ID_FAILED',

    CREATE_CAST_START: 'CREATE_CAST_START',
    CREATE_CAST_SUCCESS: 'CREATE_CAST_SUCCESS',
    CREATE_CAST_FAILED: 'CREATE_CAST_FAILED',

    UPDATE_CAST_START: 'UPDATE_CAST_START',
    UPDATE_CAST_SUCCESS: 'UPDATE_CAST_SUCCESS',
    UPDATE_CAST_FAILED: 'UPDATE_CAST_FAILED',

    DELETE_CASTS_START: 'DELETE_CASTS_START',
    DELETE_CASTS_SUCCESS: 'DELETE_CASTS_SUCCESS',
    DELETE_CASTS_FAILED: 'DELETE_CASTS_FAILED',
};

export default ACTION_TYPES;