const COUNTRIES = [
	{"code": "AF", value: "Afghanistan", label: "Afghanistan", "number": "004"},
	{"code": "AL", value: "Albania", label: "Albania", "number": "008"},
	{"code": "DZ", value: "Algeria", label: "Algeria", "number": "012"},
	{"code": "AS", value: "American Samoa", label: "American Samoa", "number": "016"},
	{"code": "AD", value: "Andorra", label: "Andorra", "number": "020"},
	{"code": "AO", value: "Angola", label: "Angola", "number": "024"},
	{"code": "AI", value: "Anguilla", label: "Anguilla", "number": "660"},
	{"code": "AQ", value: "Antarctica", label: "Antarctica", "number": "010"},
	{"code": "AG", value: "Antigua and Barbuda", label: "Antigua and Barbuda", "number": "028"},
	{"code": "AR", value: "Argentina", label: "Argentina", "number": "032"},
	{"code": "AM", value: "Armenia", label: "Armenia", "number": "051"},
	{"code": "AW", value: "Aruba", label: "Aruba", "number": "533"},
	{"code": "AU", value: "Australia", label: "Australia", "number": "036"},
	{"code": "AT", value: "Austria", label: "Austria", "number": "040"},
	{"code": "AZ", value: "Azerbaijan", label: "Azerbaijan", "number": "031"},
	{"code": "BS", value: "Bahamas", label: "Bahamas", "number": "044"},
	{"code": "BH", value: "Bahrain", label: "Bahrain", "number": "048"},
	{"code": "BD", value: "Bangladesh", label: "Bangladesh", "number": "050"},
	{"code": "BB", value: "Barbados", label: "Barbados", "number": "052"},
	{"code": "BY", value: "Belarus", label: "Belarus", "number": "112"},
	{"code": "BE", value: "Belgium", label: "Belgium", "number": "056"},
	{"code": "BZ", value: "Belize", label: "Belize", "number": "084"},
	{"code": "BJ", value: "Benin", label: "Benin", "number": "204"},
	{"code": "BM", value: "Bermuda", label: "Bermuda", "number": "060"},
	{"code": "BT", value: "Bhutan", label: "Bhutan", "number": "064"},
	{"code": "BO", value: "Bolivia (Plurinational State of)", label: "Bolivia (Plurinational State of)", "number": "068"},
	{"code": "BQ", value: "Bonaire, Sint Eustatius and Saba", label: "Bonaire, Sint Eustatius and Saba", "number": "535"},
	{"code": "BA", value: "Bosnia and Herzegovina", label: "Bosnia and Herzegovina", "number": "070"},
	{"code": "BW", value: "Botswana", label: "Botswana", "number": "072"},
	{"code": "BV", value: "Bouvet Island", label: "Bouvet Island", "number": "074"},
	{"code": "BR", value: "Brazil", label: "Brazil", "number": "076"},
	{"code": "IO", value: "British Indian Ocean Territory", label: "British Indian Ocean Territory", "number": "086"},
	{"code": "BN", value: "Brunei Darussalam", label: "Brunei Darussalam", "number": "096"},
	{"code": "BG", value: "Bulgaria", label: "Bulgaria", "number": "100"},
	{"code": "BF", value: "Burkina Faso", label: "Burkina Faso", "number": "854"},
	{"code": "BI", value: "Burundi", label: "Burundi", "number": "108"},
	{"code": "CV", value: "Cabo Verde", label: "Cabo Verde", "number": "132"},
	{"code": "KH", value: "Cambodia", label: "Cambodia", "number": "116"},
	{"code": "CM", value: "Cameroon", label: "Cameroon", "number": "120"},
	{"code": "CA", value: "Canada", label: "Canada", "number": "124"},
	{"code": "KY", value: "Cayman Islands", label: "Cayman Islands", "number": "136"},
	{"code": "CF", value: "Central African Republic", label: "Central African Republic", "number": "140"},
	{"code": "TD", value: "Chad", label: "Chad", "number": "148"},
	{"code": "CL", value: "Chile", label: "Chile", "number": "152"},
	{"code": "CN", value: "China", label: "China", "number": "156"},
	{"code": "CX", value: "Christmas Island", label: "Christmas Island", "number": "162"},
	{"code": "CC", value: "Cocos (Keeling) Islands", label: "Cocos (Keeling) Islands", "number": "166"},
	{"code": "CO", value: "Colombia", label: "Colombia", "number": "170"},
	{"code": "KM", value: "Comoros", label: "Comoros", "number": "174"},
	{"code": "CD", value: "Congo (the Democratic Republic of the)", label: "Congo (the Democratic Republic of the)", "number": "180"},
	{"code": "CG", value: "Congo", label: "Congo", "number": "178"},
	{"code": "CK", value: "Cook Islands", label: "Cook Islands", "number": "184"},
	{"code": "CR", value: "Costa Rica", label: "Costa Rica", "number": "188"},
	{"code": "HR", value: "Croatia", label: "Croatia", "number": "191"},
	{"code": "CU", value: "Cuba", label: "Cuba", "number": "192"},
	{"code": "CW", value: "Curaçao", label: "Curaçao", "number": "531"},
	{"code": "CY", value: "Cyprus", label: "Cyprus", "number": "196"},
	{"code": "CZ", value: "Czechia", label: "Czechia", "number": "203"},
	{"code": "CI", value: "Côte d'Ivoire", label: "Côte d'Ivoire", "number": "384"},
	{"code": "DK", value: "Denmark", label: "Denmark", "number": "208"},
	{"code": "DJ", value: "Djibouti", label: "Djibouti", "number": "262"},
	{"code": "DM", value: "Dominica", label: "Dominica", "number": "212"},
	{"code": "DO", value: "Dominican", label: "Dominican Republic", "number": "214"},
	{"code": "EC", value: "Ecuador", label: "Ecuador", "number": "218"},
	{"code": "EG", value: "Egypt", label: "Egypt", "number": "818"},
	{"code": "SV", value: "El Salvador", label: "El Salvador", "number": "222"},
	{"code": "GQ", value: "Equatorial Guinea", label: "Equatorial Guinea", "number": "226"},
	{"code": "ER", value: "Eritrea", label: "Eritrea", "number": "232"},
	{"code": "EE", value: "Estonia", label: "Estonia", "number": "233"},
	{"code": "SZ", value: "Eswatini", label: "Eswatini", "number": "748"},
	{"code": "ET", value: "Ethiopia", label: "Ethiopia", "number": "231"},
	{"code": "FK", value: "Falkland Islands [Malvinas]", label: "Falkland Islands [Malvinas]", "number": "238"},
	{"code": "FO", value: "Faroe Islands", label: "Faroe Islands", "number": "234"},
	{"code": "FJ", value: "Fiji", label: "Fiji", "number": "242"},
	{"code": "FI", value: "Finland", label: "Finland", "number": "246"},
	{"code": "FR", value: "France", label: "France", "number": "250"},
	{"code": "GF", value: "French Guiana", label: "French Guiana", "number": "254"},
	{"code": "PF", value: "French Polynesia", label: "French Polynesia", "number": "258"},
	{"code": "TF", value: "French Southern Territories", label: "French Southern Territories", "number": "260"},
	{"code": "GA", value: "Gabon", label: "Gabon", "number": "266"},
	{"code": "GM", value: "Gambia", label: "Gambia", "number": "270"},
	{"code": "GE", value: "Georgia", label: "Georgia", "number": "268"},
	{"code": "DE", value: "Germany", label: "Germany", "number": "276"},
	{"code": "GH", value: "Ghana", label: "Ghana", "number": "288"},
	{"code": "GI", value: "Gibraltar", label: "Gibraltar", "number": "292"},
	{"code": "GR", value: "Greece", label: "Greece", "number": "300"},
	{"code": "GL", value: "Greenland", label: "Greenland", "number": "304"},
	{"code": "GD", value: "Grenada", label: "Grenada", "number": "308"},
	{"code": "GP", value: "Guadeloupe", label: "Guadeloupe", "number": "312"},
	{"code": "GU", value: "Guam", label: "Guam", "number": "316"},
	{"code": "GT", value: "Guatemala", label: "Guatemala", "number": "320"},
	{"code": "GG", value: "Guernsey", label: "Guernsey", "number": "831"},
	{"code": "GN", value: "Guinea", label: "Guinea", "number": "324"},
	{"code": "GW", value: "Guinea-Bissau", label: "Guinea-Bissau", "number": "624"},
	{"code": "GY", value: "Guyana", label: "Guyana", "number": "328"},
	{"code": "HT", value: "Haiti", label: "Haiti", "number": "332"},
	{"code": "HM", value: "Heard Island and McDonald Islands", label: "Heard Island and McDonald Islands", "number": "334"},
	{"code": "VA", value: "Holy See", label: "Holy See", "number": "336"},
	{"code": "HN", value: "Honduras", label: "Honduras", "number": "340"},
	{"code": "HK", value: "Hong Kong", label: "Hong Kong", "number": "344"},
	{"code": "HU", value: "Hungary", label: "Hungary", "number": "348"},
	{"code": "IS", value: "Iceland", label: "Iceland", "number": "352"},
	{"code": "IN", value: "India", label: "India", "number": "356"},
	{"code": "ID", value: "Indonesia", label: "Indonesia", "number": "360"},
	{"code": "IR", value: "Iran", label: "Iran (Islamic Republic of)", "number": "364"},
	{"code": "IQ", value: "Iraq", label: "Iraq", "number": "368"},
	{"code": "IE", value: "Ireland", label: "Ireland", "number": "372"},
	{"code": "IM", value: "Isle of Man", label: "Isle of Man", "number": "833"},
	{"code": "IL", value: "Israel", label: "Israel", "number": "376"},
	{"code": "IT", value: "Italy", label: "Italy", "number": "380"},
	{"code": "JM", value: "Jamaica", label: "Jamaica", "number": "388"},
	{"code": "JP", value: "Japan", label: "Japan", "number": "392"},
	{"code": "JE", value: "Jersey", label: "Jersey", "number": "832"},
	{"code": "JO", value: "Jordan", label: "Jordan", "number": "400"},
	{"code": "KZ", value: "Kazakhstan", label: "Kazakhstan", "number": "398"},
	{"code": "KE", value: "Kenya", label: "Kenya", "number": "404"},
	{"code": "KI", value: "Kiribati", label: "Kiribati", "number": "296"},
	{"code": "KP", value: "Korea (the Democratic People's Republic of)", label: "Korea (the Democratic People's Republic of)", "number": "408"},
	{"code": "KR", value: "Korea (the Republic of)", label: "Korea (the Republic of)", "number": "410"},
	{"code": "KW", value: "Kuwait", label: "Kuwait", "number": "414"},
	{"code": "KG", value: "Kyrgyzstan", label: "Kyrgyzstan", "number": "417"},
	{"code": "LA", value: "Lao People's Democratic Republic", label: "Lao People's Democratic Republic", "number": "418"},
	{"code": "LV", value: "Latvia", label: "Latvia", "number": "428"},
	{"code": "LB", value: "Lebanon", label: "Lebanon", "number": "422"},

	{"code": "LS", value: "Lesotho", label: "Lesotho", "number": "426"},
	{"code": "LR", value: "Liberia", label: "Liberia", "number": "430"},
	{"code": "LY", value: "Libya", label: "Libya", "number": "434"},
	{"code": "LI", value: "Liechtenstein", label: "Liechtenstein", "number": "438"},
	{"code": "LT", value: "Lithuania", label: "Lithuania", "number": "440"},
	{"code": "LU", value: "Luxembourg", label: "Luxembourg", "number": "442"},
	{"code": "MO", value: "Macao", label: "Macao", "number": "446"},
	{"code": "MG", value: "Madagascar", label: "Madagascar", "number": "450"},
	{"code": "MW", value: "Malawi", label: "Malawi", "number": "454"},
	{"code": "MY", value: "Malaysia", label: "Malaysia", "number": "458"},
	{"code": "MV", value: "Maldives", label: "Maldives", "number": "462"},
	{"code": "ML", value: "Mali", label: "Mali", "number": "466"},
	{"code": "MT", value: "Malta", label: "Malta", "number": "470"},
	{"code": "MH", value: "Marshall Islands", label: "Marshall Islands", "number": "584"},
	{"code": "MQ", value: "Martinique", label: "Martinique", "number": "474"},
	{"code": "MR", value: "Mauritania", label: "Mauritania", "number": "478"},
	{"code": "MU", value: "Mauritius", label: "Mauritius", "number": "480"},
	{"code": "YT", value: "Mayotte", label: "Mayotte", "number": "175"},
	{"code": "MX", value: "Mexico", label: "Mexico", "number": "484"},
	{"code": "FM", value: "Micronesia (Federated States of)", label: "Micronesia (Federated States of)", "number": "583"},
	{"code": "MD", value: "Moldova (the Republic of)", label: "Moldova (the Republic of)", "number": "498"},
	{"code": "MC", value: "Monaco", label: "Monaco", "number": "492"},
	{"code": "MN", value: "Mongolia", label: "Mongolia", "number": "496"},
	{"code": "ME", value: "Montenegro", label: "Montenegro", "number": "499"},
	{"code": "MS", value: "Montserrat", label: "Montserrat", "number": "500"},
	{"code": "MA", value: "Morocco", label: "Morocco", "number": "504"},
	{"code": "MZ", value: "Mozambique", label: "Mozambique", "number": "508"},
	{"code": "MM", value: "Myanmar", label: "Myanmar", "number": "104"},
	{"code": "NA", value: "Namibia", label: "Namibia", "number": "516"},
	{"code": "NR", value: "Nauru", label: "Nauru", "number": "520"},
	{"code": "NP", value: "Nepal", label: "Nepal", "number": "524"},
	{"code": "NL", value: "Netherlands", label: "Netherlands", "number": "528"},
	{"code": "NC", value: "New Caledonia", label: "New Caledonia", "number": "540"},
	{"code": "NZ", value: "New Zealand", label: "New Zealand", "number": "554"},
	{"code": "NI", value: "Nicaragua", label: "Nicaragua", "number": "558"},
	{"code": "NE", value: "Niger", label: "Niger", "number": "562"},
	{"code": "NG", value: "Nigeria", label: "Nigeria", "number": "566"},
	{"code": "NU", value: "Niue", label: "Niue", "number": "570"},
	{"code": "NF", value: "Norfolk Island", label: "Norfolk Island", "number": "574"},
	{"code": "MP", value: "Northern Mariana Islands", label: "Northern Mariana Islands", "number": "580"},
	{"code": "NO", value: "Norway", label: "Norway", "number": "578"},
	{"code": "OM", value: "Oman", label: "Oman", "number": "512"},
	{"code": "PK", value: "Pakistan", label: "Pakistan", "number": "586"},
	{"code": "PW", value: "Palau", label: "Palau", "number": "585"},
	{"code": "PS", value: "Palestine, State of", label: "Palestine, State of", "number": "275"},
	{"code": "PA", value: "Panama", label: "Panama", "number": "591"},
	{"code": "PG", value: "Papua New Guinea", label: "Papua New Guinea", "number": "598"},
	{"code": "PY", value: "Paraguay", label: "Paraguay", "number": "600"},
	{"code": "PE", value: "Peru", label: "Peru", "number": "604"},
	{"code": "PH", value: "Philippines", label: "Philippines", "number": "608"},
	{"code": "PN", value: "Pitcairn", label: "Pitcairn", "number": "612"},
	{"code": "PL", value: "Poland", label: "Poland", "number": "616"},
	{"code": "PT", value: "Portugal", label: "Portugal", "number": "620"},
	{"code": "PR", value: "Puerto Rico", label: "Puerto Rico", "number": "630"},
	{"code": "QA", value: "Qatar", label: "Qatar", "number": "634"},
	{"code": "MK", value: "Republic of North Macedonia", label: "Republic of North Macedonia", "number": "807"},
	{"code": "RO", value: "Romania", label: "Romania", "number": "642"},
	{"code": "RU", value: "Russian Federation", label: "Russian Federation", "number": "643"},
	{"code": "RW", value: "Rwanda", label: "Rwanda", "number": "646"},
	{"code": "RE", value: "Réunion", label: "Réunion", "number": "638"},
	{"code": "BL", value: "Saint Barthélemy", label: "Saint Barthélemy", "number": "652"},
	{"code": "SH", value: "Saint Helena, Ascension and Tristan da Cunha", label: "Saint Helena, Ascension and Tristan da Cunha", "number": "654"},
	{"code": "KN", value: "Saint Kitts and Nevis", label: "Saint Kitts and Nevis", "number": "659"},
	{"code": "LC", value: "Saint Lucia", label: "Saint Lucia", "number": "662"},
	{"code": "MF", value: "Saint Martin (French part)", label: "Saint Martin (French part)", "number": "663"},
	{"code": "PM", value: "Saint Pierre and Miquelon", label: "Saint Pierre and Miquelon", "number": "666"},
	{"code": "VC", value: "Saint Vincent and the Grenadines", label: "Saint Vincent and the Grenadines", "number": "670"},
	{"code": "WS", value: "Samoa", label: "Samoa", "number": "882"},
	{"code": "SM", value: "San Marino", label: "San Marino", "number": "674"},
	{"code": "ST", value: "Sao Tome and Principe", label: "Sao Tome and Principe", "number": "678"},
	{"code": "SA", value: "Saudi Arabia", label: "Saudi Arabia", "number": "682"},
	{"code": "SN", value: "Senegal", label: "Senegal", "number": "686"},
	{"code": "RS", value: "Serbia", label: "Serbia", "number": "688"},
	{"code": "SC", value: "Seychelles", label: "Seychelles", "number": "690"},
	{"code": "SL", value: "Sierra Leone", label: "Sierra Leone", "number": "694"},
	{"code": "SG", value: "Singapore", label: "Singapore", "number": "702"},
	{"code": "SX", value: "Sint Maarten (Dutch part)", label: "Sint Maarten (Dutch part)", "number": "534"},
	{"code": "SK", value: "Slovakia", label: "Slovakia", "number": "703"},
	{"code": "SI", value: "Slovenia", label: "Slovenia", "number": "705"},
	{"code": "SB", value: "Solomon Islands", label: "Solomon Islands", "number": "090"},
	{"code": "SO", value: "Somalia", label: "Somalia", "number": "706"},
	{"code": "ZA", value: "South Africa", label: "South Africa", "number": "710"},
	{"code": "GS", value: "South Georgia and the South Sandwich Islands", label: "South Georgia and the South Sandwich Islands", "number": "239"},
	{"code": "SS", value: "South Sudan", label: "South Sudan", "number": "728"},
	{"code": "ES", value: "Spain", label: "Spain", "number": "724"},
	{"code": "LK", value: "Sri Lanka", label: "Sri Lanka", "number": "144"},
	{"code": "SD", value: "Sudan", label: "Sudan", "number": "729"},
	{"code": "SR", value: "Surilabel", label: "Surilabel", "number": "740"},
	{"code": "SJ", value: "Svalbard and Jan Mayen", label: "Svalbard and Jan Mayen", "number": "744"},
	{"code": "SE", value: "Sweden", label: "Sweden", "number": "752"},
	{"code": "CH", value: "Switzerland", label: "Switzerland", "number": "756"},
	{"code": "SY", value: "Syrian Arab Republic", label: "Syrian Arab Republic", "number": "760"},
	{"code": "TW", value: "Taiwan", label: "Taiwan", "number": "158"},
	{"code": "TJ", value: "Tajikistan", label: "Tajikistan", "number": "762"},
	{"code": "TZ", value: "Tanzania, United Republic of", label: "Tanzania, United Republic of", "number": "834"},
	{"code": "TH", value: "Thailand", label: "Thailand", "number": "764"},
	{"code": "TL", value: "Timor-Leste", label: "Timor-Leste", "number": "626"},
	{"code": "TG", value: "Togo", label: "Togo", "number": "768"},
	{"code": "TK", value: "Tokelau", label: "Tokelau", "number": "772"},
	{"code": "TO", value: "Tonga", label: "Tonga", "number": "776"},
	{"code": "TT", value: "Trinidad and Tobago", label: "Trinidad and Tobago", "number": "780"},
	{"code": "TN", value: "Tunisia", label: "Tunisia", "number": "788"},
	{"code": "TR", value: "Turkey", label: "Turkey", "number": "792"},
	{"code": "TM", value: "Turkmenistan", label: "Turkmenistan", "number": "795"},
	{"code": "TC", value: "Turks and Caicos Islands", label: "Turks and Caicos Islands", "number": "796"},
	{"code": "TV", value: "Tuvalu", label: "Tuvalu", "number": "798"},
	{"code": "UG", value: "Uganda", label: "Uganda", "number": "800"},
	{"code": "UA", value: "Ukraine", label: "Ukraine", "number": "804"},
	{"code": "AE", value: "United Arab Emirates", label: "United Arab Emirates", "number": "784"},
	{"code": "GB", value: "United Kingdom of Great Britain and Northern Ireland", label: "United Kingdom of Great Britain and Northern Ireland", "number": "826"},
	{"code": "UM", value: "United States Minor Outlying Islands", label: "United States Minor Outlying Islands", "number": "581"},
	{"code": "US", value: "United States of America", label: "United States of America", "number": "840"},
	{"code": "UY", value: "Uruguay", label: "Uruguay", "number": "858"},
	{"code": "UZ", value: "Uzbekistan", label: "Uzbekistan", "number": "860"},
	{"code": "VU", value: "Vanuatu", label: "Vanuatu", "number": "548"},
	{"code": "VE", value: "Venezuela (Bolivarian Republic of)", label: "Venezuela (Bolivarian Republic of)", "number": "862"},
	{"code": "VN", value: "Viet Nam", label: "Viet Nam", "number": "704"},
	{"code": "VG", value: "Virgin Islands (British)", label: "Virgin Islands (British)", "number": "092"},
	{"code": "VI", value: "Virgin Islands (U.S.)", label: "Virgin Islands (U.S.)", "number": "850"},
	{"code": "WF", value: "Wallis and Futuna", label: "Wallis and Futuna", "number": "876"},
	{"code": "EH", value: "Western Sahara", label: "Western Sahara", "number": "732"},
	{"code": "YE", value: "Yemen", label: "Yemen", "number": "887"},
	{"code": "ZM", value: "Zambia", label: "Zambia", "number": "894"},
	{"code": "ZW", value: "Zimbabwe", label: "Zimbabwe", "number": "716"},
	{"code": "AX", value: "Åland Islands", label: "Åland Islands", "number": "248"}
];

export default COUNTRIES