const LANGUAGES = 
[
        {  value: 'Abkhazian', label: 'Abkhazian'},
        { value: 'Afar', label: 'Afar'},
        { value: 'Afrikaans', label: 'Afrikaans'},
        {  value: 'Akan', label: 'Akan'},
        { value: 'Albanian', label: 'Albanian'},
        { value: 'Amharic', label: 'Amharic'},
        { value: 'Arabic', label: 'Arabic'},
        { value: 'Aragonese', label: 'Aragonese'},
        { value: 'Armenian', label: 'Armenian'},
        { value: 'Assamese', label: 'Assamese'},
        { value: 'Avaric', label: 'Avaric'},
        { value: 'Avestan', label: 'Avestan'},
        { value: 'Aymara', label: 'Aymara'},
        { value: 'Azerbaijani', label: 'Azerbaijani'},
        { value: 'Bambara', label: 'Bambara'},
        { value: 'Bashkir', label: 'Bashkir'},
        { value: 'Basque', label: 'Basque'},
        { value: 'Belarusian', label: 'Belarusian'},
        { value: 'Bengali (Bangla)', label: 'Bengali (Bangla)'},
        { value: 'Bihari', label: 'Bihari'},
        { value: 'Bislama', label: 'Bislama'},
        { value: 'Bosnian', label: 'Bosnian'},
        { value: 'Breton', label: 'Breton'},
        { value: 'Bulgarian', label: 'Bulgarian'},
        { value: 'Burmese', label: 'Burmese'},
        { value: 'Catalan', label: 'Catalan'},
        { value: 'Chamorro', label: 'Chamorro'},
        { value: 'Chechen', label: 'Chechen'},
        // { label: 'Chichewa, Chewa, Nyanja', 'ny'},
        // { label: 'Chinese', 'zh'},
        // { label: 'Chinese (Simplified)', 'zh-Hans'},
        // { label: 'Chinese (Traditional)', 'zh-Hant'},
        // { label: 'Chuvash', 'cv'},
        // { label: 'Cornish', 'kw'},
        // { label: 'Corsican', 'co'},
        // { label: 'Cree', 'cr'},
        // { label: 'Croatian', 'hr'},
        // { label: 'Czech', 'cs'},
        // { label: 'Danish', 'da'},
        // { label: 'Divehi, Dhivehi, Maldivian', 'dv'},
        // { label: 'Dutch', 'nl'},
        // { label: 'Dzongkha', 'dz'},
        // { label: 'English', 'en'},
        // { label: 'Esperanto', 'eo'},
        // { label: 'Estonian', 'et'},
        // { label: 'Ewe', 'ee'},
        // { label: 'Faroese', 'fo'},
        // { label: 'Fijian', 'fj'},
        // { label: 'Finnish', 'fi'},
        // { label: 'French', 'fr'},
        // { label: 'Fula, Fulah, Pulaar, Pular', 'ff'},
        // { label: 'Galician', 'gl'},
        // { label: 'Gaelic (Scottish)', 'gd'},
        // { label: 'Gaelic (Manx)', 'gv'},
        // { label: 'Georgian', 'ka'},
        // { label: 'German', 'de'},
        // { label: 'Greek', 'el'},
        // { label: 'Greenlandic', 'kl'},
        // { label: 'Guarani', 'gn'},
        // { label: 'Gujarati', 'gu'},
        // { label: 'Haitian Creole', 'ht'},
        // { label: 'Hausa', 'ha'},
        // { label: 'Hebrew', 'he'},
        // { label: 'Herero', 'hz'},
        // { label: 'Hindi', 'hi'},
        // { label: 'Hiri Motu', 'ho'},
        // { label: 'Hungarian', 'hu'},
        // { label: 'Icelandic', 'is'},
        // { label: 'Ido', 'io'},
        // { label: 'Igbo', 'ig'},
        // { label: 'Indonesian', 'id, in'},
        // { label: 'Interlingua', 'ia'},
        // { label: 'Interlingue', 'ie'},
        // { label: 'Inuktitut', 'iu'},
        // { label: 'Inupiak', 'ik'},
        // { label: 'Irish', 'ga'},
        // { label: 'Italian', 'it'},
        // { label: 'Japanese', 'ja'},
        // { label: 'Javanese', 'jv'},
        // { label: 'Kalaallisut, Greenlandic', 'kl'},
        // { label: 'Kannada', 'kn'},
        // { label: 'Kanuri', 'kr'},
        // { label: 'Kashmiri', 'ks'},
        // { label: 'Kazakh', 'kk'},
        // { label: 'Khmer', 'km'},
        // { label: 'Kikuyu', 'ki'},
        // { label: 'Kinyarwanda (Rwanda)', 'rw'},
        // { label: 'Kirundi', 'rn'},
        // { label: 'Kyrgyz', 'ky'},
        // { label: 'Komi', 'kv'},
        // { label: 'Kongo', 'kg'},
        // { label: 'Korean', 'ko'},
        // { label: 'Kurdish', 'ku'},
        // { label: 'Kwanyama', 'kj'},
        // { label: 'Lao', 'lo'},
        // { label: 'Latin', 'la'},
        // { label: 'Latvian (Lettish)', 'lv'},
        // { label: 'Limburgish ( Limburger)', 'li'},
        // { label: 'Lingala', 'ln'},
        // { label: 'Lithuanian', 'lt'},
        // { label: 'Luga-Katanga', 'lu'},
        // { label: 'Luganda, Ganda', 'lg'},
        // { label: 'Luxembourgish', 'lb'},
        // { label: 'Manx', 'gv'},
        // { label: 'Macedonian', 'mk'},
        // { label: 'Malagasy', 'mg'},
        // { label: 'Malay', 'ms'},
        // { label: 'Malayalam', 'ml'},
        // { label: 'Maltese', 'mt'},
        // { label: 'Maori', 'mi'},
        // { label: 'Marathi', 'mr'},
        // { label: 'Marshallese', 'mh'},
        // { label: 'Moldavian', 'mo'},
        // { label: 'Mongolian', 'mn'},
        // { label: 'Nauru', 'na'},
        // { label: 'Navajo', 'nv'},
        // { label: 'Ndonga', 'ng'},
        // { label: 'Northern Ndebele', 'nd'},
        // { label: 'Nepali', 'ne'},
        // { label: 'Norwegian', 'no'},
        // { label: 'Norwegian bokmål', 'nb'},
        // { label: 'Norwegian nynorsk', 'nn'},
        // { label: 'Nuosu', 'ii'},
        // { label: 'Occitan', 'oc'},
        // { label: 'Ojibwe', 'oj'},
        // { label: 'Old Church Slavonic, Old Bulgarian', 'cu'},
        // { label: 'Oriya', 'or'},
        // { label: 'Oromo (Afaan Oromo)', 'om'},
        // { label: 'Ossetian', 'os'},
        // { label: 'Pāli', 'pi'},
        // { label: 'Pashto, Pushto', 'ps'},
        // { label: 'Persian (Farsi)', 'fa'},
        // { label: 'Polish', 'pl'},
        // { label: 'Portuguese', 'pt'},
        // { label: 'Punjabi (Eastern)', 'pa'},
        // { label: 'Quechua', 'qu'},
        // { label: 'Romansh', 'rm'},
        // { label: 'Romanian', 'ro'},
        // { label: 'Russian', 'ru'},
        // { label: 'Sami', 'se'},
        // { label: 'Samoan', 'sm'},
        // { label: 'Sango', 'sg'},
        // { label: 'Sanskrit', 'sa'},
        // { label: 'Serbian', 'sr'},
        // { label: 'Serbo-Croatian', 'sh'},
        // { label: 'Sesotho', 'st'},
        // { label: 'Setswana', 'tn'},
        // { label: 'Shona', 'sn'},
        // { label: 'Sichuan Yi', 'ii'},
        // { label: 'Sindhi', 'sd'},
        // { label: 'Sinhalese', 'si'},
        // { label: 'Siswati', 'ss'},
        // { label: 'Slovak', 'sk'},
        // { label: 'Slovenian', 'sl'},
        // { label: 'Somali', 'so'},
        // { label: 'Southern Ndebele', 'nr'},
        // { label: 'Spanish', 'es'},
        // { label: 'Sundanese', 'su'},
        // { label: 'Swahili (Kiswahili)', 'sw'},
        // { label: 'Swati', 'ss'},
        // { label: 'Swedish', 'sv'},
        // { label: 'Tagalog', 'tl'},
];

export default LANGUAGES