const ACTION_TYPES = 
{
    FETCH_DASHBOARD_DATA_START: 'FETCH_DASHBOARD_DATA_START',
    FETCH_DASHBOARD_DATA_SUCCESS: 'FETCH_DASHBOARD_DATA_SUCCESS',
    FETCH_DASHBOARD_DATA_FAILED: 'FETCH_DASHBOARD_DATA_FAILED'
}

export default ACTION_TYPES