const ACTION_TYPES = 
{
    FETCH_ALL_EMPLOYEES_START: 'FETCH_ALL_EMPLOYEES_START',
    FETCH_ALL_EMPLOYEES_SUCCESS: 'FETCH_ALL_EMPLOYEES_SUCCESS',
    FETCH_ALL_EMPLOYEES_FAILED: 'FETCH_ALL_EMPLOYEES_FAILED',
    
    CLEAR_EMPLOYEE_ERRORS: 'CLEAR_EMPLOYEE_ERRORS'
};

export default ACTION_TYPES;