const ACTION_TYPES = 
{
    FETCH_ALL_GENRES_START: 'FETCH_ALL_GENRES_START',
    FETCH_ALL_GENRES_SUCCESS: 'FETCH_ALL_GENRES_SUCCESS',
    FETCH_ALL_GENRES_FAILED: 'FETCH_ALL_GENRES_FAILED',

    FIND_GENRE_BY_ID_START: 'FIND_GENRE_BY_ID_START',
    FIND_GENRE_BY_ID_SUCCESS: 'FIND_GENRE_BY_ID_SUCCESS',
    FIND_GENRE_BY_ID_FAILED: 'FIND_GENRE_BY_ID_FAILED',

    CREATE_GENRE_START: 'CREATE_GENRE_START',
    CREATE_GENRE_SUCCESS: 'CREATE_GENRE_SUCCESS',
    CREATE_GENRE_FAILED: 'CREATE_GENRE_FAILED',

    UPDATE_GENRE_START: 'UPDATE_GENRE_START',
    UPDATE_GENRE_SUCCESS: 'UPDATE_GENRE_SUCCESS',
    UPDATE_GENRE_FAILED: 'UPDATE_GENRE_FAILED',

    RESTORE_GENRES_START: 'RESTORE_GENRES_START',
    RESTORE_GENRES_SUCCESS: 'RESTORE_GENRES_SUCCESS',
    RESTORE_GENRES_FAILED: 'RESTORE_GENRES_FAILED',

    TOGGLE_GENRE_ENABLED_START: 'TOGGLE_GENRE_ENABLED_START',
    TOGGLE_GENRE_ENABLED_SUCCESS: 'TOGGLE_GENRE_ENABLED_SUCCESS',
    TOGGLE_GENRE_ENABLED_FAILED: 'TOGGLE_GENRE_ENABLED_FAILED',

    DELETE_GENRES_START: 'DELETE_GENRES_START',
    DELETE_GENRES_SUCCESS: 'DELETE_GENRES_SUCCESS',
    DELETE_GENRES_FAILED: 'DELETE_GENRES_FAILED',

    CLEAR_GENRE_ERRORS: 'CLEAR_GENRE_ERRORS',
};

export default ACTION_TYPES;