const ACTION_TYPES = 
{
    FETCH_ALL_GENRES_START: 'FETCH_ALL_GENRES_START',
    FETCH_ALL_GENRES_SUCCESS: 'FETCH_ALL_GENRES_SUCCESS',
    FETCH_ALL_GENRES_FAILED: 'FETCH_ALL_GENRES_FAILED',

    FIND_GENRE_BY_ID_START: 'FIND_GENRE_BY_ID_START',
    FIND_GENRE_BY_ID_SUCCESS: 'FIND_GENRE_BY_ID_SUCCESS',
    FIND_GENRE_BY_ID_FAILED: 'FIND_GENRE_BY_ID_FAILED',

    CREATE_GENRE_START: 'CREATE_GENRE_START',
    CREATE_GENRE_SUCCESS: 'CREATE_GENRE_SUCCESS',
    CREATE_GENRE_FAILED: 'CREATE_GENRE_FAILED',

    UPDATE_GENRE_START: 'UPDATE_GENRE_START',
    UPDATE_GENRE_SUCCESS: 'UPDATE_GENRE_SUCCESS',
    UPDATE_GENRE_FAILED: 'UPDATE_GENRE_FAILED',

    DELETE_GENRES_START: 'DELETE_GENRES_START',
    DELETE_GENRES_SUCCESS: 'DELETE_GENRES_SUCCESS',
    DELETE_GENRES_FAILED: 'DELETE_GENRES_FAILED',
};

export default ACTION_TYPES;