const ACTION_TYPES = 
{
    FETCH_ALL_MOVIES_START: 'FETCH_ALL_MOVIES_START',
    FETCH_ALL_MOVIES_SUCCESS: 'FETCH_ALL_MOVIES_SUCCESS',
    FETCH_ALL_MOVIES_FAILED: 'FETCH_ALL_MOVIES_FAILED',

    FIND_MOVIE_BY_ID_START: 'FIND_MOVIE_BY_ID_START',
    FIND_MOVIE_BY_ID_SUCCESS: 'FIND_MOVIE_BY_ID_SUCCESS',
    FIND_MOVIE_BY_ID_FAILED: 'FIND_MOVIE_BY_ID_FAILED',

    CREATE_MOVIE_START: 'CREATE_MOVIE_START',
    CREATE_MOVIE_SUCCESS: 'CREATE_MOVIE_SUCCESS',
    CREATE_MOVIE_FAILED: 'CREATE_MOVIE_FAILED',

    UPDATE_MOVIE_START: 'UPDATE_MOVIE_START',
    UPDATE_MOVIE_SUCCESS: 'UPDATE_MOVIE_SUCCESS',
    UPDATE_MOVIE_FAILED: 'UPDATE_MOVIE_FAILED',

    DELETE_MOVIES_START: 'DELETE_MOVIES_START',
    DELETE_MOVIES_SUCCESS: 'DELETE_MOVIES_SUCCESS',
    DELETE_MOVIES_FAILED: 'DELETE_MOVIES_FAILED',

    CLEAR_MOVIE_ERRORS: 'CLEAR_MOVIE_ERRORS',
    UPDATE_MOVIE_ERROR_STATE: 'UPDATE_MOVIE_ERROR_STATE',
};

export default ACTION_TYPES;