const ACTION_TYPES = 
{
    FETCH_ALL_DIRECTORS_START: 'FETCH_ALL_DIRECTORS_START',
    FETCH_ALL_DIRECTORS_SUCCESS: 'FETCH_ALL_DIRECTORS_SUCCESS',
    FETCH_ALL_DIRECTORS_FAILED: 'FETCH_ALL_DIRECTORS_FAILED',

    FIND_DIRECTOR_BY_ID_START: 'FIND_DIRECTOR_BY_ID_START',
    FIND_DIRECTOR_BY_ID_SUCCESS: 'FIND_DIRECTOR_BY_ID_SUCCESS',
    FIND_DIRECTOR_BY_ID_FAILED: 'FIND_DIRECTOR_BY_ID_FAILED',

    CREATE_DIRECTOR_START: 'CREATE_DIRECTOR_START',
    CREATE_DIRECTOR_SUCCESS: 'CREATE_DIRECTOR_SUCCESS',
    CREATE_DIRECTOR_FAILED: 'CREATE_DIRECTOR_FAILED',

    UPDATE_DIRECTOR_START: 'UPDATE_DIRECTOR_START',
    UPDATE_DIRECTOR_SUCCESS: 'UPDATE_DIRECTOR_SUCCESS',
    UPDATE_DIRECTOR_FAILED: 'UPDATE_DIRECTOR_FAILED',

    TOGGLE_DIRECTOR_ENABLED_START: 'TOGGLE_DIRECTOR_ENABLED_START',
    TOGGLE_DIRECTOR_ENABLED_SUCCESS: 'TOGGLE_DIRECTOR_ENABLED_SUCCESS',
    TOGGLE_DIRECTOR_ENABLED_FAILED: 'TOGGLE_DIRECTOR_ENABLED_FAILED',

    DELETE_DIRECTORS_START: 'DELETE_DIRECTORS_START',
    DELETE_DIRECTORS_SUCCESS: 'DELETE_DIRECTORS_SUCCESS',
    DELETE_DIRECTORS_FAILED: 'DELETE_DIRECTORS_FAILED',

    CLEAR_DIRECTOR_ERRORS: 'CLEAR_DIRECTOR_ERRORS'
};

export default ACTION_TYPES;