const ACTION_TYPES = 
{
    FETCH_ALL_COMING_SOON_MOVIES_START: 'FETCH_ALL_COMING_SOON_MOVIES_START',
    FETCH_ALL_COMING_SOON_MOVIES_SUCCESS: 'FETCH_ALL_COMING_SOON_MOVIES_SUCCESS',
    FETCH_ALL_COMING_SOON_MOVIES_FAILED: 'FETCH_ALL_COMING_SOON_MOVIES_FAILED',

    FIND_COMING_SOON_MOVIE_BY_ID_START: 'FIND_COMING_SOON_MOVIE_BY_ID_START',
    FIND_COMING_SOON_MOVIE_BY_ID_SUCCESS: 'FIND_COMING_SOON_MOVIE_BY_ID_SUCCESS',
    FIND_COMING_SOON_MOVIE_BY_ID_FAILED: 'FIND_COMING_SOON_MOVIE_BY_ID_FAILED',

    CREATE_COMING_SOON_MOVIE_START: 'CREATE_COMING_SOON_MOVIE_START',
    CREATE_COMING_SOON_MOVIE_SUCCESS: 'CREATE_COMING_SOON_MOVIE_SUCCESS',
    CREATE_COMING_SOON_MOVIE_FAILED: 'CREATE_COMING_SOON_MOVIE_FAILED',
    
    CREATE_TRAILER_START: 'CREATE_TRAILER_START',
    CREATE_TRAILER_SUCCESS: 'CREATE_TRAILER_SUCCESS',
    CREATE_TRAILER_FAILED: 'CREATE_TRAILER_FAILED',

    UPDATE_COMING_SOON_MOVIE_START: 'UPDATE_COMING_SOON_MOVIE_START',
    UPDATE_COMING_SOON_MOVIE_SUCCESS: 'UPDATE_COMING_SOON_MOVIE_SUCCESS',
    UPDATE_COMING_SOON_MOVIE_FAILED: 'UPDATE_COMING_SOON_MOVIE_FAILED',

    RESTORE_COMING_SOON_MOVIES_START: 'RESTORE_COMING_SOON_MOVIES_START',
    RESTORE_COMING_SOON_MOVIES_SUCCESS: 'RESTORE_COMING_SOON_MOVIES_SUCCESS',
    RESTORE_COMING_SOON_MOVIES_FAILED: 'RESTORE_COMING_SOON_MOVIES_FAILED',
    
    UPDATE_TRAILER_START: 'UPDATE_TRAILER_START',
    UPDATE_TRAILER_SUCCESS: 'UPDATE_TRAILER_SUCCESS',
    UPDATE_TRAILER_FAILED: 'UPDATE_TRAILER_FAILED',

    DELETE_COMING_SOON_MOVIES_START: 'DELETE_COMING_SOON_MOVIES_START',
    DELETE_COMING_SOON_MOVIES_SUCCESS: 'DELETE_COMING_SOON_MOVIES_SUCCESS',
    DELETE_COMING_SOON_MOVIES_FAILED: 'DELETE_COMING_SOON_MOVIES_FAILED',

    DELETE_TRAILER_START: 'DELETE_TRAILER_START',
    DELETE_TRAILER_SUCCESS: 'DELETE_TRAILER_SUCCESS',
    DELETE_TRAILER_FAILED: 'DELETE_TRAILER_FAILED',

    TOGGLE_COMING_SOON_MOVIE_RELEASE_START: 'TOGGLE_COMING_SOON_MOVIE_RELEASE_START',
    TOGGLE_COMING_SOON_MOVIE_RELEASE_SUCCESS: 'TOGGLE_COMING_SOON_MOVIE_RELEASE_SUCCESS',
    TOGGLE_COMING_SOON_MOVIE_RELEASE_FAILED: 'TOGGLE_COMING_SOON_MOVIE_RELEASE_FAILED',

    CLEAR_COMING_SOON_MOVIE_ERRORS: 'CLEAR_COMING_SOON_MOVIE_ERRORS',
    UPDATE_COMING_SOON_MOVIE_ERROR_STATE: 'UPDATE_COMING_SOON_MOVIE_ERROR_STATE',

    CLEAR_TRAILER_ERRORS: 'CLEAR_TRAILER_ERRORS',
    UPDATE_TRAILER_ERROR_STATE: 'UPDATE_TRAILER_ERROR_STATE',
};

export default ACTION_TYPES;